version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - '8080:8080'
    tty: true
    init: true
    privileged: true
    volumes:
      - ./:/var/www:cached
